import React from 'react';
import { ArrowLeft, Zap, Layers } from 'lucide-react';

export default function Integrations({ onNavigate }) {
  
  const integrationList = [
    { name: 'Zapier', description: 'Connect IncDrops to thousands of other apps.' },
    { name: 'Slack', description: 'Send content ideas directly to your Slack channels.' },
    { name: 'Hootsuite', description: 'Push ideas to your content calendar.' },
    { name: 'Buffer', description: 'Schedule posts generated by IncDrops.' },
    { name: 'Google Sheets', description: 'Export your saved ideas automatically.' },
    { name: 'Airtable', description: 'Organize your content in a powerful database.' },
  ];

  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <header className="border-b border-gray-800 backdrop-blur-md sticky top-0 z-40 bg-black/80">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <button
              onClick={() => onNavigate('landing')}
              className="p-2 hover:bg-gray-800 rounded-lg transition-all duration-300 hover:scale-110"
              title="Back to home"
            >
              <ArrowLeft size={24} className="text-gray-400 hover:text-gray-200" />
            </button>
            <h1 className="text-2xl font-bold bg-gradient-to-r from-gray-300 via-gray-100 to-gray-400 bg-clip-text text-transparent">
              IncDrops
            </h1>
          </div>
        </div>
      </header>

      {/* Content */}
      <div className="max-w-5xl mx-auto px-6 py-12">
        <h2 className="text-5xl font-bold mb-8 text-center bg-gradient-to-r from-gray-300 via-gray-100 to-gray-400 bg-clip-text text-transparent">
          Integrations
        </h2>
        <p className="text-xl text-center text-gray-400 mb-12">
          Connect IncDrops to your favorite tools and automate your workflow.
        </p>

        {/* Integration Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {integrationList.map((integration) => (
            <div 
              key={integration.name}
              className="bg-gray-900 border border-gray-700 rounded-2xl p-8 shadow-xl hover:shadow-gray-700/50 hover:border-gray-600 transition-all duration-300 flex flex-col items-center text-center"
            >
              <div className="p-4 bg-gray-800 rounded-xl mb-6">
                <Layers size={32} className="text-gray-300" />
              </div>
              <h3 className="text-2xl font-semibold text-white mb-3">{integration.name}</h3>
              <p className="text-gray-400 flex-1 mb-6">{integration.description}</p>
              <button className="w-full px-5 py-2 bg-gray-700 hover:bg-gray-600 rounded-lg font-semibold transition-all duration-300">
                Learn More
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
